# name of the software
name: Python-DNN
#
description: Python Deep Neural Network ToolKit
# current version of the software
version: 1.0.1
# url of the download button
downloadUrl: https://github.com/IITM-DONLAB/python-dnn
# licence of the software
license: Apache License
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

githubUrl: https://github.com/IITM-DONLAB/python-dnn

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/IITM-DONLAB/python-dnn

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/IITM-DONLAB/python-dnn
  - title: Issues
    url: https://github.com/IITM-DONLAB/python-dnn/issues?state=open

# header
header:
  color1: "#080331"
  color2: "#673051"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: IITM-DONLAB
  repo: python-dnn

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: true
  profileUrl:


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
