#! /bin/sh
# Copyright 2014    G.K SUDHARSHAN <sudharpun90@gmail.com>  IIT Madras
# Copyright 2014    Abil N George<mail@abilng.in>   IIT Madras
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
# WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
# MERCHANTABLITY OR NON-INFRINGEMENT.
# See the Apache 2 License for the specific language governing permissions and
# limitations under the License.


usage(){
    echo "Usage: $0 CONFIG_FILE"
    echo " "
}

DNN_HOME=src/

if [ $# -ne 1 ] ; then
    usage
    exit 1
fi

case "$1" in
    --help|-h)
        usage
        exit 0
    ;;
    -*)
        echo "$0: invalid option $1"
        usage
        exit 1
    ;;
    *)
        if [ ! -f $1 ]; then
            echo "Config File: '$1' not found!"
            exit 2
        fi
        /usr/bin/env python2.7 ${DNN_HOME}/main.py $@
    ;;
esac
